### ISSUE TITLE
[Week-10] Formatting problem at the end of instruction

### ISSUE THREAD

**Issue by tashrifbillah** [CS171/Homework_instructions#5]
Hi @cnobre ,

After `4. Clip all elements that go beyond the borders of your chart area`, most of the texts got **incorrectly** marked down in [week-10_lab.md](https://github.com/CS171/Homework_instructions/blob/master/week-10/lab/week-10_lab.md). The reason being:

![image](https://user-images.githubusercontent.com/35086881/97794384-9bbd8080-1bcf-11eb-9cc4-400e4065e7c9.png)

At line 471, If you hit two tabs before ` ``` ` , the problem should be fixed. I would love to do that for you, but my last PR is still not merged so unable to fork again and make this small correction :(

**Comment by tashrifbillah** [comment]
For what it's worth, I gave Robert a few suggestions in [this commit](https://github.com/CS171/Homework_instructions/commit/376963a4698e112581b29833934f556fba0c4cb1#diff-a87e0e366220f4026556c631547197b8e8a4cb9953830d4f342e519b7b0fbf97) about efficiently coding `.md` files that should reduce writing effort.

**Comment by kruegert** [comment]
fixed it. Thanks for pointing it out!
